# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_excel整理计划表_图形界面20181026.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 80, 120, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_get_input_file = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_get_input_file.setObjectName("pushButton_get_input_file")
        self.verticalLayout_2.addWidget(self.pushButton_get_input_file)
        self.pushButton_get_output_file = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_get_output_file.setObjectName("pushButton_get_output_file")
        self.verticalLayout_2.addWidget(self.pushButton_get_output_file)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(330, 80, 120, 100))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_get_input_file_all_in_1 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_get_input_file_all_in_1.setObjectName("pushButton_get_input_file_all_in_1")
        self.verticalLayout_4.addWidget(self.pushButton_get_input_file_all_in_1)
        self.pushButton_get_output_file_all_in_1 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_get_output_file_all_in_1.setObjectName("pushButton_get_output_file_all_in_1")
        self.verticalLayout_4.addWidget(self.pushButton_get_output_file_all_in_1)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(570, 80, 120, 100))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_get_input_file_finality = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_get_input_file_finality.setObjectName("pushButton_get_input_file_finality")
        self.verticalLayout_5.addWidget(self.pushButton_get_input_file_finality)
        self.pushButton_get_output_file_finality = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_get_output_file_finality.setObjectName("pushButton_get_output_file_finality")
        self.verticalLayout_5.addWidget(self.pushButton_get_output_file_finality)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(80, 50, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(330, 50, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(570, 50, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.textBrowse_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowse_info.setObjectName("textBrowse_info")
        self.verticalLayout.addWidget(self.textBrowse_info)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_2.setBuddy(self.textBrowse_info)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "资金计划表辅助工具"))
        self.label_2.setText(_translate("MainWindow", "信息窗口："))
        self.pushButton_get_input_file.setText(_translate("MainWindow", "选择导入文件"))
        self.pushButton_get_output_file.setText(_translate("MainWindow", "保存文件"))
        self.pushButton_get_input_file_all_in_1.setText(_translate("MainWindow", "选择导入文件"))
        self.pushButton_get_output_file_all_in_1.setText(_translate("MainWindow", "保存文件"))
        self.pushButton_get_input_file_finality.setText(_translate("MainWindow", "选择导入文件"))
        self.pushButton_get_output_file_finality.setText(_translate("MainWindow", "保存文件"))
        self.label.setText(_translate("MainWindow", "分行上报表"))
        self.label_3.setText(_translate("MainWindow", "各行明细表"))
        self.label_4.setText(_translate("MainWindow", "总行下达表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "计划表格一维化"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "其他功能"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "其他功能"))

